# Generated by Django 5.0.2 on 2024-11-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew_assignments', '0001_initial'),
        ('flight_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('crew_members', models.ManyToManyField(related_name='flight_schedules', to='crew_assignments.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_routes.flight')),
            ],
        ),
    ]
