# Generated by Django 5.0.2 on 2024-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0002_alter_crewmember_role_flightschedule_and_more'),
        ('flight_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='crew_members',
            field=models.ManyToManyField(related_name='schedules_for_member', to='crew_assignments.crewmember'),
        ),
    ]
