# Generated by Django 5.0.2 on 2024-11-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedules', '0002_alter_flightschedule_crew_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='schedule_id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
