# Generated by Django 5.1.3 on 2024-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedules', '0005_alter_flightschedule_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='schedule_id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
