# Generated by Django 5.0.2 on 2024-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('travel_duration', models.DurationField()),
                ('departure_time', models.TimeField()),
            ],
        ),
    ]
