# Generated by Django 5.1.2 on 2024-12-02 12:37

import django.core.validators
import flight_routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(default=flight_routes.models.generate_flight_id, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('origin', models.CharField(choices=[('Manila, Philippines', 'Manila, Philippines'), ('New York, USA', 'New York, USA'), ('London, UK', 'London, UK'), ('Tokyo, Japan', 'Tokyo, Japan')], default='Manila, Philippines', max_length=255)),
                ('destination', models.CharField(choices=[('Manila, Philippines', 'Manila, Philippines'), ('New York, USA', 'New York, USA'), ('London, UK', 'London, UK'), ('Tokyo, Japan', 'Tokyo, Japan')], default='Manila, Philippines', max_length=255)),
                ('travel_duration_hours', models.IntegerField(default=0, error_messages={'max_value': 'Travel duration hours cannot exceed 23.', 'min_value': 'Travel duration hours cannot be less than 0.'}, help_text='Duration in hours (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('travel_duration_minutes', models.IntegerField(default=0, error_messages={'max_value': 'Travel duration minutes cannot exceed 59.', 'min_value': 'Travel duration minutes cannot be less than 0.'}, help_text='Duration in minutes (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('departure_time', models.TimeField(default='00:00')),
            ],
        ),
    ]
