# Generated by Django 5.0.2 on 2024-11-11 18:14

import datetime
import flight_routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(choices=[('Manila, Philippines', 'Manila, Philippines'), ('New York, USA', 'New York, USA'), ('London, UK', 'London, UK'), ('Tokyo, Japan', 'Tokyo, Japan')], default='Manila, Philippines', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(default=flight_routes.models.generate_flight_id, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(choices=[('Manila, Philippines', 'Manila, Philippines'), ('New York, USA', 'New York, USA'), ('London, UK', 'London, UK'), ('Tokyo, Japan', 'Tokyo, Japan')], default='Manila, Philippines', max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='travel_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
