# Generated by Django 5.0.2 on 2024-11-12 10:04

import flight_routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0003_alter_flight_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(default=flight_routes.models.generate_flight_id, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
