# Generated by Django 5.0.2 on 2024-11-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0007_alter_flight_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(default='YA4461', editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
