# Generated by Django 5.0.2 on 2024-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0015_alter_flight_flight_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='travel_duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='travel_duration_hours',
            field=models.IntegerField(default=0, help_text='Duration in hours'),
        ),
        migrations.AddField(
            model_name='flight',
            name='travel_duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
    ]
