# Generated by Django 5.0.2 on 2024-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0016_remove_flight_travel_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='travel_duration_hours',
            field=models.IntegerField(default=0, help_text='Duration in hours', max_length=2),
        ),
        migrations.AlterField(
            model_name='flight',
            name='travel_duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration in minutes', max_length=2),
        ),
    ]
