# Generated by Django 5.0.2 on 2024-11-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0018_alter_flight_travel_duration_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='travel_duration_hours',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='travel_duration_minutes',
        ),
    ]
