# Generated by Django 5.0.2 on 2024-11-12 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0019_remove_flight_travel_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='travel_duration_hours',
            field=models.IntegerField(default=0, help_text='Duration in hours (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='flight',
            name='travel_duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration in minutes (0-59)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
