# Generated by Django 5.1.3 on 2024-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0002_alter_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitem',
            name='item_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
