# Generated by Django 5.1.3 on 2024-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_booking', '0003_alter_additionalitem_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalitem',
            name='item_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
