# Generated by Django 5.1.2 on 2024-12-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('first_name', models.CharField(max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('crew_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('Captain', 'Captain'), ('First Officer', 'First Officer'), ('Flight Attendant', 'Flight Attendant'), ('Flight Engineer', 'Flight Engineer')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
