# Generated by Django 5.0.2 on 2024-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('schedule_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('crew_members', models.ManyToManyField(related_name='flight_schedule_crew_members', to='crew_assignments.crewmember')),
            ],
        ),
        migrations.AddField(
            model_name='crewmember',
            name='flight_schedules',
            field=models.ManyToManyField(related_name='crew_members_in_schedule', to='crew_assignments.flightschedule'),
        ),
    ]
