# Generated by Django 5.1.2 on 2024-12-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew_assignments', '0001_initial'),
        ('flight_schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='flight_schedules',
            field=models.ManyToManyField(related_name='crew_members_in_schedule', to='flight_schedules.flightschedule'),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='crew_members',
            field=models.ManyToManyField(related_name='flight_schedule_crew_members', to='crew_assignments.crewmember'),
        ),
    ]
