# Generated by Django 5.0.2 on 2024-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0002_alter_crewmember_role_flightschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
