# Generated by Django 5.0.2 on 2024-11-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0003_alter_crewmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='role',
            field=models.CharField(choices=[('Captain', 'Captain'), ('First Officer', 'First Officer'), ('Flight Attendant', 'Flight Attendant'), ('Flight Engineer', 'Flight Engineer')], max_length=100),
        ),
    ]
