# Generated by Django 5.0.2 on 2024-11-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0004_alter_crewmember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='crew_id',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
