# Generated by Django 5.0.2 on 2024-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0006_alter_crewmember_crew_id'),
        ('flight_schedules', '0002_alter_flightschedule_crew_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='flight_schedules',
            field=models.ManyToManyField(related_name='crew_members_in_schedule', to='flight_schedules.flightschedule'),
        ),
    ]
