# Generated by Django 5.0.2 on 2024-11-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0007_alter_crewmember_flight_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
