# Generated by Django 5.0.2 on 2024-11-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0008_crewmember_first_name_crewmember_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
