# Generated by Django 5.1.3 on 2024-11-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_assignments', '0009_crewmember_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
